# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  Joint1:
    has_velocity_limits: true
    max_velocity: 3.490656
    has_acceleration_limits: true
    max_acceleration: 17.567841
    has_jerk: true
    max_jerk: 892.0286289
  Joint2:
    has_velocity_limits: true
    max_velocity: 3.490656
    has_acceleration_limits: true
    max_acceleration: 2.101232
    has_jerk: true
    max_jerk: 886.576821
  Joint3:
    has_velocity_limits: true
    max_velocity: 3.490656
    has_acceleration_limits: true
    max_acceleration: 10.738869
    has_jerk: true
    max_jerk: 516.588450
  Joint4:
    has_velocity_limits: true
    max_velocity: 5.235983
    has_acceleration_limits: true
    max_acceleration: 27.276282
    has_jerk: true
    max_jerk: 175.806183
  Joint5:
    has_velocity_limits: true
    max_velocity: 5.235983
    has_acceleration_limits: true
    max_acceleration: 21.786787
    has_jerk: true
    max_jerk: 156.995898
  Joint6:
    has_velocity_limits: true
    max_velocity: 5.235983
    has_acceleration_limits: true
    max_acceleration: 112.291689
    has_jerk: true
    max_jerk: 57.552859