# The service definition for a chess move

# Request
int8 start_x
int8 start_y
int8 end_x
int8 end_y
bool clash
#string piece  # 'knight', 'pawn', etc.

---

# Response
bool success  # indicate if the move was successful
string message  # additional message, if any
